// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAaSmjVsf28hULjUktjW2DnqjBG5o_-ls',
    appId: '1:656972122227:web:fae7062f12ce51d1e84206',
    messagingSenderId: '656972122227',
    projectId: 'erangaapp-8beda',
    authDomain: 'erangaapp-8beda.firebaseapp.com',
    storageBucket: 'erangaapp-8beda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm765VrbWVLJXIfiVgcgthKzSi4YHsCI8',
    appId: '1:656972122227:android:4525d6341ac138b1e84206',
    messagingSenderId: '656972122227',
    projectId: 'erangaapp-8beda',
    storageBucket: 'erangaapp-8beda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVVBdXfJz8O8fyCJy7c4WPDMB8MdVKiM',
    appId: '1:656972122227:ios:be80bdf6467bd6c1e84206',
    messagingSenderId: '656972122227',
    projectId: 'erangaapp-8beda',
    storageBucket: 'erangaapp-8beda.appspot.com',
    androidClientId: '656972122227-oprm2hvdcjgocoevq6rvr48u30doukvh.apps.googleusercontent.com',
    iosClientId: '656972122227-6a0v0tf4qb3r194sn844jptg5gacs33k.apps.googleusercontent.com',
    iosBundleId: 'com.example.erangaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzVVBdXfJz8O8fyCJy7c4WPDMB8MdVKiM',
    appId: '1:656972122227:ios:be80bdf6467bd6c1e84206',
    messagingSenderId: '656972122227',
    projectId: 'erangaapp-8beda',
    storageBucket: 'erangaapp-8beda.appspot.com',
    androidClientId: '656972122227-oprm2hvdcjgocoevq6rvr48u30doukvh.apps.googleusercontent.com',
    iosClientId: '656972122227-6a0v0tf4qb3r194sn844jptg5gacs33k.apps.googleusercontent.com',
    iosBundleId: 'com.example.erangaapp',
  );
}
